version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mi_postgres1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: midb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jakarta:
    build:
      context: ./upd.edu.ec
    container_name: mi_jakarta1
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/midb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  angular:
    build:
      context: ./unversidadfront
    container_name: mi_angular1
    ports:
      - "4200:80"
    depends_on:
      - jakarta

volumes:
  pgdata:
